# Generated by Django 5.2.4 on 2025-07-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profiledetails_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiledetails",
            name="occupation",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
