# Generated by Django 5.2.4 on 2025-07-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profiledetails_experience_profiledetails_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profiledetails",
            old_name="skillowned",
            new_name="skill",
        ),
    ]
