# Generated by Django 5.2.4 on 2025-07-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_skillowned_profiledetails_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiledetails",
            name="achievements",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profiledetails",
            name="description",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profiledetails",
            name="workLink",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
