# Generated by Django 5.2.4 on 2025-07-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profiledetails_achievements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiledetails",
            name="experience",
            field=models.IntegerField(default=0),
        ),
    ]
